### ISSUE TITLE
Join our forces

### ISSUE THREAD

**Issue by alex-lairan** [moba1/maybe#1]
Hello !

I just saw you created a lib for monads in Crystal.

Can we join our forces by maintaining this lib together ? https://github.com/alex-lairan/monads 

This one supports Maybe, Either (Result) and List.

**Comment by moba1** [comment]
@alex-lairan Can I join your team?

**Comment by alex-lairan** [comment]
Yes, do you prefer an invitation to the project, or create an organisation ?

**Comment by moba1** [comment]
invitation

**Comment by alex-lairan** [comment]
Ok, I invited you ! :) 

Let's make monads for crystal together ! :muscle: 

For the moment, the API is nearly the same as Dry-monads from Ruby, but it can change.
